# Generated by Django 5.2.7 on 2026-10-02 14:18

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='spécialité')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
            ],
            options={
                'verbose_name': 'spécialité',
                'verbose_name_plural': 'spécialités',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-().]{6,20}$', 'Numéro de téléphone invalide : chiffres, espaces, +, - uniquement.')], verbose_name='téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='photo')),
                ('locale', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=8, verbose_name='langue')),
                ('is_platform_staff', models.BooleanField(default=False, help_text='Accès à toutes les cliniques et à la configuration globale.', verbose_name='administrateur plateforme')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de notification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=160, verbose_name='nom')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='raison sociale')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identifiant')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(blank=True, default='Maroc', max_length=80, verbose_name='pays')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-().]{6,20}$', 'Numéro de téléphone invalide : chiffres, espaces, +, - uniquement.')], verbose_name='téléphone')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-().]{6,20}$', 'Numéro de téléphone invalide : chiffres, espaces, +, - uniquement.')], verbose_name='urgence')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('tax_identifier', models.CharField(blank=True, max_length=60, verbose_name='identifiant fiscal')),
                ('license_number', models.CharField(blank=True, max_length=60, verbose_name="numéro d'agrément")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/', verbose_name='logo')),
                ('currency', models.CharField(default='MAD', max_length=8, verbose_name='devise')),
                ('timezone', models.CharField(default='Africa/Casablanca', max_length=64, verbose_name='fuseau horaire')),
                ('language', models.CharField(default='fr', max_length=8, verbose_name='langue')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taux de TVA par défaut')),
                ('appointment_slot_minutes', models.PositiveSmallIntegerField(default=20, verbose_name="durée d'un créneau (min)")),
                ('dunning_days', models.PositiveSmallIntegerField(default=15, help_text='Délai avant relance automatique des factures échues.', verbose_name='relance impayé après (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'clinique',
                'verbose_name_plural': 'cliniques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identifiant public')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('RECEPTION', 'Accueil'), ('DOCTOR', 'Médecin'), ('NURSE', 'Infirmier'), ('ACCOUNTANT', 'Comptable')], max_length=16, verbose_name='rôle')),
                ('employee_number', models.CharField(blank=True, max_length=32, verbose_name='matricule')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="date d'embauche")),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='fin de contrat')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='salaire de base')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.clinic', verbose_name='clinique')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'membre du personnel',
                'verbose_name_plural': 'membres du personnel',
                'ordering': ['clinic__name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='début')),
                ('end_at', models.DateTimeField(verbose_name='fin')),
                ('reason', models.CharField(blank=True, max_length=160, verbose_name='motif')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='accounts.membership', verbose_name='praticien')),
            ],
            options={
                'verbose_name': 'indisponibilité',
                'verbose_name_plural': 'indisponibilités',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(validators=[django.core.validators.RegexValidator('^([01]\\d|2[0-3]):[0-5]\\d$', 'Heure invalide.')], verbose_name='de')),
                ('end_time', models.TimeField(validators=[django.core.validators.RegexValidator('^([01]\\d|2[0-3]):[0-5]\\d$', 'Heure invalide.')], verbose_name='à')),
                ('is_closed', models.BooleanField(default=False, verbose_name='fermé')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='accounts.membership', verbose_name='praticien')),
            ],
            options={
                'verbose_name': "horaire d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('DOCTOR', 'Médecin'), ('NURSE', 'Infirmier')], max_length=16, verbose_name='profession')),
                ('license_number', models.CharField(blank=True, max_length=60, verbose_name='n° de licence')),
                ('diploma', models.CharField(blank=True, max_length=160, verbose_name='diplôme')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, verbose_name="années d'expérience")),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('consultation_duration_minutes', models.PositiveSmallIntegerField(default=20, verbose_name='durée de consultation (min)')),
                ('calendar_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='couleur agenda')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profile', to='accounts.membership', verbose_name='membre')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='accounts.specialty', verbose_name='spécialité')),
            ],
            options={
                'verbose_name': 'profil professionnel',
                'verbose_name_plural': 'profils professionnels',
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'clinic'), name='uniq_membership_user_clinic'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number', ''), _negated=True), fields=('clinic', 'employee_number'), name='uniq_employee_number_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='blockedslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='ck_blocked_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='openinghour',
            constraint=models.UniqueConstraint(fields=('membership', 'weekday'), name='uniq_opening_hour_per_day'),
        ),
        migrations.AddConstraint(
            model_name='openinghour',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('is_closed', True), _connector='OR'), name='ck_opening_hour_end_after_start'),
        ),
    ]
