# Generated by Django 5.2.7 on 2026-10-02 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='salaire de base'),
        ),
    ]
