# Generated by Django 5.2.7 on 2026-10-02 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('kind', models.CharField(help_text='Ex. : patient, invoice, claim, prescription.', max_length=32, verbose_name='type de document')),
                ('period', models.CharField(default='', max_length=16, verbose_name='période')),
                ('prefix', models.CharField(max_length=16, verbose_name='préfixe')),
                ('digits', models.PositiveSmallIntegerField(default=4, verbose_name='nombre de chiffres')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='dernier numéro attribué')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rel', to='accounts.clinic', verbose_name='clinique')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'compteur de séquence',
                'verbose_name_plural': 'compteurs de séquence',
                'constraints': [models.UniqueConstraint(fields=('clinic', 'kind', 'period'), name='uniq_sequence_per_clinic_kind_period')],
            },
        ),
    ]
