# Generated by Django 5.2.7 on 2026-10-02 15:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_membership_base_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Décocher pour archiver sans supprimer.', verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255, verbose_name="motif d'archivage")),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identifiant public')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('reference', models.CharField(blank=True, editable=False, help_text='Numéro de dossier attribué automatiquement (PT-AAAA-00001).', max_length=32, verbose_name='référence')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Femme'), ('M', 'Homme'), ('O', 'Autre')], max_length=1, verbose_name='sexe')),
                ('cin', models.CharField(blank=True, help_text="Carte d'identité nationale.", max_length=12, validators=[django.core.validators.RegexValidator(message='Format de CIN invalide (ex. : AB123456).', regex='^[A-Z]{1,2}\\d{1,6}$')], verbose_name='CIN')),
                ('passport', models.CharField(blank=True, max_length=20, verbose_name='passeport')),
                ('social_security', models.CharField(blank=True, max_length=20, verbose_name='numéro de sécurité sociale')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, verbose_name="contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="téléphone d'urgence")),
                ('insurer', models.CharField(blank=True, max_length=120, verbose_name='mutuelle / assureur')),
                ('insurance_number', models.CharField(blank=True, max_length=40, verbose_name="numéro d'adhésion")),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='fin de validité')),
                ('is_insured', models.BooleanField(default=False, verbose_name='assuré')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A positif'), ('A-', 'A négatif'), ('B+', 'B positif'), ('B-', 'B négatif'), ('AB+', 'AB positif'), ('AB-', 'AB négatif'), ('O+', 'O positif'), ('O-', 'O négatif'), ('', 'Inconnu')], default='', max_length=3, verbose_name='groupe sanguin')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='taille (cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)], verbose_name='poids (kg)')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies connues')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='maladies chroniques')),
                ('current_medication', models.TextField(blank=True, verbose_name='traitement en cours')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='grossesse en cours')),
                ('preferred_language', models.CharField(default='fr', max_length=8, verbose_name='langue parlée')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rel', to='accounts.clinic', verbose_name='clinique')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['clinic', 'last_name', 'first_name'], name='patients_pa_clinic__d8fe94_idx'), models.Index(fields=['clinic', 'reference'], name='patients_pa_clinic__3e121f_idx'), models.Index(fields=['clinic', 'phone'], name='patients_pa_clinic__c795cb_idx'), models.Index(fields=['clinic', 'birth_date'], name='patients_pa_clinic__eafe88_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'reference'), name='uniq_patient_reference_per_clinic')],
            },
        ),
    ]
