# Generated by Django 5.2.7 on 2026-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, default='fr', max_length=8, verbose_name='langue parlée'),
        ),
    ]
