# Generated by Django 5.2.7 on 2026-10-02 16:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_membership_base_salary'),
        ('patients', '0002_alter_patient_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Décocher pour archiver sans supprimer.', verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255, verbose_name="motif d'archivage")),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('reference', models.CharField(blank=True, editable=False, help_text='Numéro de rendez-vous attribué automatiquement (RDV-AAAA-00001).', max_length=32, verbose_name='référence')),
                ('start_at', models.DateTimeField(verbose_name='début')),
                ('end_at', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('PENDING', 'À confirmer'), ('CONFIRMED', 'Confirmé'), ('ARRIVED', 'Arrivé'), ('IN_PROGRESS', 'En consultation'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Absent')], default='PENDING', max_length=16, verbose_name='statut')),
                ('kind', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CONTROL', 'Contrôle'), ('URGENCY', 'Urgence'), ('VACCINATION', 'Vaccination'), ('PROCEDURE', 'Acte technique'), ('OTHER', 'Autre')], default='CONSULTATION', max_length=16, verbose_name='type')),
                ('reason', models.CharField(blank=True, max_length=160, verbose_name='motif')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation")),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='Renseigné par le jalon 5 (notifications).', null=True, verbose_name='rappel envoyé le')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rel', to='accounts.clinic', verbose_name='clinique')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='patient')),
                ('practitioner', models.ForeignKey(help_text='Médecin ou infirmier qui reçoit le patient.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.membership', verbose_name='praticien')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='le')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='appointments.appointment', verbose_name='rendez-vous')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='annulé par')),
            ],
            options={
                'verbose_name': 'annulation',
                'verbose_name_plural': 'annulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'start_at'], name='appointment_clinic__becf05_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['practitioner', 'start_at'], name='appointment_practit_33af52_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'start_at'], name='appointment_patient_4b5ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'status'], name='appointment_clinic__02f124_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('clinic', 'reference'), name='uniq_appointment_reference_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='ck_appointment_end_after_start'),
        ),
    ]
